const https = require('https');
const fs = require('fs');
const path = require('path');

// Load certificates generated by mkcert
const options = {
    key: fs.readFileSync('.cert/localhost.key'),
    cert: fs.readFileSync('.cert/localhost.crt'),
};

const PORT = 5500;

const mimeTypes = {
    '.html': 'text/html',
    '.js': 'text/javascript',
    '.css': 'text/css',
    '.json': 'application/json',
    '.png': 'image/png',
    '.jpg': 'image/jpg',
    '.gif': 'image/gif',
    '.svg': 'image/svg+xml',
    '.wav': 'audio/wav',
    '.mp4': 'video/mp4',
    '.woff': 'application/font-woff',
    '.ttf': 'application/font-ttf',
    '.eot': 'application/vnd.ms-fontobject',
    '.otf': 'application/font-otf',
    '.wasm': 'application/wasm',
};

https.createServer(options, (req, res) => {
    console.log(`request: ${req.url}`);

    // CRITICAL: Headers to allow access from Webflow (or any other origin)
    // and satisfy Chrome's "Private Network Access" checks.
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', '*');
    res.setHeader('Access-Control-Allow-Private-Network', 'true'); // <--- THE KEY FIX

    // Handle preflight requests
    if (req.method === 'OPTIONS') {
        res.writeHead(204);
        res.end();
        return;
    }

    // Basic static file serving
    let filePath = '.' + req.url;
    if (filePath === './') filePath = './index.html';

    const extname = String(path.extname(filePath)).toLowerCase();
    const contentType = mimeTypes[extname] || 'application/octet-stream';

    fs.readFile(filePath, (error, content) => {
        if (error) {
            if (error.code === 'ENOENT') {
                res.writeHead(404);
                res.end('File not found: ' + filePath);
            } else {
                res.writeHead(500);
                res.end('Server error: ' + error.code);
            }
        } else {
            res.writeHead(200, { 'Content-Type': contentType });
            res.end(content, 'utf-8');
        }
    });

}).listen(PORT, () => {
    console.log('---------------------------------------------------');
    console.log(`Local Secure Server running at: https://localhost:${PORT}/`);
    console.log('---------------------------------------------------');
    console.log('CORS & Private Network Access headers ENABLED.');
    console.log('Hit Ctrl+C to stop.');
});
